"""
FIFA World Cup 2026 - Estructura del bracket y asignacion de terceros.
Generado desde el fixture oficial FIFA (WCup_2026_4.2.6_en.xlsx, hojas
'Matches' y 'AssignThird', FIFA 23.06.2025).

- GROUPS: equipos por grupo (nombres tal como estan en la BD, ApiEquipo.nombre)
- R32_TEMPLATE: ronda de 32 -> slots ('1A' = 1ro grupo A, '2B' = 2do grupo B,
  '3-ABCDF' = mejor tercero de uno de esos grupos segun THIRD_ASSIGN)
- KO_TEMPLATE: rondas posteriores -> 'W73' = ganador del partido 73,
  'RU101' = perdedor del partido 101
- THIRD_ASSIGN: combinacion de 8 grupos cuyos terceros clasifican (string de
  letras ordenadas) -> {slot: grupo del tercero asignado}
- api_fixture_id en BD = 9_000_000 + numero de partido FIFA
"""

FIXTURE_ID_BASE = 9_000_000  # api_fixture_id = FIXTURE_ID_BASE + match_no

GROUPS = {
    "A": ["Mexico", "South Africa", "Rep. of Korea", "Czech Rep."],
    "B": ["Canada", "Bosnia/Herzeg.", "Qatar", "Switzerland"],
    "C": ["Brazil", "Morocco", "Haiti", "Scotland"],
    "D": ["USA", "Paraguay", "Australia", "Turkey"],
    "E": ["Germany", "Curaçao", "Ivory Coast", "Ecuador"],
    "F": ["Netherlands", "Japan", "Sweden", "Tunisia"],
    "G": ["Belgium", "Egypt", "IR Iran", "New Zealand"],
    "H": ["Spain", "Cape Verde", "Saudi Arabia", "Uruguay"],
    "I": ["France", "Senegal", "Iraq", "Norway"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "DR Congo", "Uzbekistan", "Colombia"],
    "L": ["England", "Croatia", "Ghana", "Panama"],
}

# Ronda de 32: numero de partido FIFA -> (slot local, slot visitante)
R32_TEMPLATE = {
    73: ("2A", "2B"),
    74: ("1E", "3-ABCDF"),
    75: ("1F", "2C"),
    76: ("1C", "2F"),
    77: ("1I", "3-CDFGH"),
    78: ("2E", "2I"),
    79: ("1A", "3-CEFHI"),
    80: ("1L", "3-EHIJK"),
    81: ("1D", "3-BEFIJ"),
    82: ("1G", "3-AEHIJ"),
    83: ("2K", "2L"),
    84: ("1H", "2J"),
    85: ("1B", "3-EFGIJ"),
    86: ("1J", "2H"),
    87: ("1K", "3-DEIJL"),
    88: ("2D", "2G"),
}

# Rondas posteriores: numero de partido -> (slot local, slot visitante, ronda)
KO_TEMPLATE = {
    89:  ("W74", "W77", "Round of 16"),
    90:  ("W73", "W75", "Round of 16"),
    91:  ("W76", "W78", "Round of 16"),
    92:  ("W79", "W80", "Round of 16"),
    93:  ("W83", "W84", "Round of 16"),
    94:  ("W81", "W82", "Round of 16"),
    95:  ("W86", "W88", "Round of 16"),
    96:  ("W85", "W87", "Round of 16"),
    97:  ("W89", "W90", "Quarter-Final"),
    98:  ("W93", "W94", "Quarter-Final"),
    99:  ("W91", "W92", "Quarter-Final"),
    100: ("W95", "W96", "Quarter-Final"),
    101: ("W97", "W98", "Semi-Final"),
    102: ("W99", "W100", "Semi-Final"),
    103: ("RU101", "RU102", "Third Place"),
    104: ("W101", "W102", "Final"),
}

# Tabla oficial FIFA: que tercero juega en cada slot segun los 8 grupos
# cuyos terceros clasifican. Clave: letras ordenadas, ej. "ABCDEFGH".
THIRD_ASSIGN = {
    "ABCDEFGH": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "E"},
    "ABCDEFGI": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABCDEFGJ": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "J"},
    "ABCDEFGK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABCDEFGL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCDEFHI": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "I"},
    "ABCDEFHJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "E"},
    "ABCDEFHK": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "K"},
    "ABCDEFHL": {"3-CEFHI": "H", "3-EFGIJ": "F", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCDEFIJ": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABCDEFIK": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDEFIL": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDEFJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABCDEFJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCDEFKL": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDEGHI": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABCDEGHJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "J"},
    "ABCDEGHK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABCDEGHL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCDEGIJ": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "J"},
    "ABCDEGIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDEGIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDEGJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "J", "3-EHIJK": "K"},
    "ABCDEGJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "J"},
    "ABCDEGKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDEHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABCDEHIK": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDEHIL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDEHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABCDEHJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCDEHKL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDEIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDEIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDEIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDEJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDFGHI": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "I"},
    "ABCDFGHJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "J"},
    "ABCDFGHK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "K"},
    "ABCDFGHL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "H"},
    "ABCDFGIJ": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "J"},
    "ABCDFGIK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDFGIL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDFGJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "J", "3-EHIJK": "K"},
    "ABCDFGJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "J"},
    "ABCDFGKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDFHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "I"},
    "ABCDFHIK": {"3-CEFHI": "H", "3-EFGIJ": "F", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDFHIL": {"3-CEFHI": "H", "3-EFGIJ": "F", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDFHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "K"},
    "ABCDFHJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "H"},
    "ABCDFHKL": {"3-CEFHI": "H", "3-EFGIJ": "F", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDFIJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDFIJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDFIKL": {"3-CEFHI": "C", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDFJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "J"},
    "ABCDGHIK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDGHIL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "J", "3-EHIJK": "K"},
    "ABCDGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "J"},
    "ABCDGHKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDGIJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDGIJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDGIKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDGJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCDHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCDHIKL": {"3-CEFHI": "H", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCDIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEFGHI": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABCEFGHJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "J"},
    "ABCEFGHK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABCEFGHL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCEFGIJ": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "J"},
    "ABCEFGIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCEFGIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCEFGJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "J", "3-EHIJK": "K"},
    "ABCEFGJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "J"},
    "ABCEFGKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEFHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABCEFHIK": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCEFHIL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCEFHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABCEFHJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCEFHKL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEFIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCEFIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCEFIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEFJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABCEGHIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCEGHIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCEGHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABCEGHJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABCEGHKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEGIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCEGIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCEGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "C", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEGJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCEHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCEHIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCEIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "C", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "J"},
    "ABCFGHIK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCFGHIL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "J", "3-EHIJK": "K"},
    "ABCFGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "J"},
    "ABCFGHKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCFGIJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCFGIJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCFGIKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCFGJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCFHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCFHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCFHIKL": {"3-CEFHI": "H", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCFHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCFIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABCGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABCGHIKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABCHIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEFGHI": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABDEFGHJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "J"},
    "ABDEFGHK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABDEFGHL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABDEFGIJ": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "J"},
    "ABDEFGIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDEFGIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDEFGJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "J", "3-EHIJK": "K"},
    "ABDEFGJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "J"},
    "ABDEFGKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEFHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABDEFHIK": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDEFHIL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDEFHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABDEFHJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABDEFHKL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEFIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDEFIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDEFIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEFJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABDEGHIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDEGHIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDEGHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABDEGHJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABDEGHKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEGIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDEGIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDEGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEGJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDEHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDEHIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDEIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "J"},
    "ABDFGHIK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDFGHIL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "J", "3-EHIJK": "K"},
    "ABDFGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "J"},
    "ABDFGHKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDFGIJK": {"3-CEFHI": "F", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDFGIJL": {"3-CEFHI": "F", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDFGIKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDFGJKL": {"3-CEFHI": "F", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDFHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDFHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDFHIKL": {"3-CEFHI": "H", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDFHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDFIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABDGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABDGHIKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABDHIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ABEFGHIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABEFGHIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABEFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ABEFGHJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ABEFGHKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEFGIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABEFGIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABEFGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEFGJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEFHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABEFHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABEFHIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEFHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEFIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABEGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABEGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABEHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABFGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ABFGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ABFGHIKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABFGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABFGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABFHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ABGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "A", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEFGHI": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "I"},
    "ACDEFGHJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "E"},
    "ACDEFGHK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "K"},
    "ACDEFGHL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ACDEFGIJ": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ACDEFGIK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDEFGIL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDEFGJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ACDEFGJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ACDEFGKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEFHIJ": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "I"},
    "ACDEFHIK": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDEFHIL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDEFHJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "K"},
    "ACDEFHJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ACDEFHKL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEFIJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDEFIJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDEFIKL": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEFJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ACDEGHIK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDEGHIL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDEGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ACDEGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ACDEGHKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEGIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDEGIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDEGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEGJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDEHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDEHIKL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDEIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "I"},
    "ACDFGHIK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDFGHIL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "K"},
    "ACDFGHJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "H"},
    "ACDFGHKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDFGIJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDFGIJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDFGIKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDFGJKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDFHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDFHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDFHIKL": {"3-CEFHI": "H", "3-EFGIJ": "F", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDFHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "F", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDFIJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACDGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACDGHIKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACDHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ACEFGHIK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACEFGHIL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACEFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ACEFGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ACEFGHKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEFGIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACEFGIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACEFGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEFGJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEFHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACEFHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACEFHIKL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEFHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEFIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACEGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACEGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACEHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACFGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ACFGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ACFGHIKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACFGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACFGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACFHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ACGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "ADEFGHIK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ADEFGHIL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ADEFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "ADEFGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "ADEFGHKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEFGIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ADEFGIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ADEFGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEFGJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEFHIJK": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ADEFHIJL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ADEFHIKL": {"3-CEFHI": "H", "3-EFGIJ": "E", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEFHJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEFIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ADEGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ADEGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADEHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADFGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "ADFGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "ADFGHIKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADFGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADFGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADFHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "ADGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "AEFGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "I", "3-EHIJK": "K"},
    "AEFGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "I"},
    "AEFGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "AEFGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "AEFGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "AEFHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "AEGHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "A", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "AFGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "F", "3-AEHIJ": "A", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEFGHI": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "BCDEFGHJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "E"},
    "BCDEFGHK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "BCDEFGHL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "BCDEFGIJ": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "BCDEFGIK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "E", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDEFGIL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "E", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDEFGJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "BCDEFGJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "BCDEFGKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "E", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEFHIJ": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "BCDEFHIK": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDEFHIL": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDEFHJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "BCDEFHJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "BCDEFHKL": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEFIJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "E", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDEFIJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "E", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDEFIKL": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEFJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "E", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "I"},
    "BCDEGHIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDEGHIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDEGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "E", "3-EHIJK": "K"},
    "BCDEGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "E"},
    "BCDEGHKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEGIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDEGIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDEGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEGJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDEHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDEHIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDEIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "I"},
    "BCDFGHIK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDFGHIL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "D", "3-EHIJK": "K"},
    "BCDFGHJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "J"},
    "BCDFGHKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDFGIJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDFGIJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDFGIKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDFGJKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDFHIJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDFHIJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDFHIKL": {"3-CEFHI": "C", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDFHJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDFIJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCDGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCDGHIKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCDHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "BCEFGHIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCEFGHIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCEFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "BCEFGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "BCEFGHKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEFGIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCEFGIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCEFGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEFGJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEFHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCEFHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCEFHIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEFHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEFIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCEGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCEGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCEHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCFGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BCFGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BCFGHIKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCFGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCFGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCFHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BCGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "C", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEFGHIJ": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "BDEFGHIK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BDEFGHIL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BDEFGHJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "BDEFGHJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "BDEFGHKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEFGIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BDEFGIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BDEFGIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEFGJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEFHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BDEFHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BDEFHIKL": {"3-CEFHI": "E", "3-EFGIJ": "I", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEFHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEFIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BDEGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BDEGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDEHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDFGHIJK": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BDFGHIJL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BDFGHIKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDFGHJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDFGIJKL": {"3-CEFHI": "I", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDFHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BDGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BEFGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "I", "3-EHIJK": "K"},
    "BEFGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "I"},
    "BEFGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BEFGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BEFGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BEFHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "I", "3-CDFGH": "H", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BEGHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "B", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "BFGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "J", "3-BEFIJ": "B", "3-ABCDF": "F", "3-AEHIJ": "I", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEFGHIJ": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "I"},
    "CDEFGHIK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "CDEFGHIL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "CDEFGHJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "E", "3-EHIJK": "K"},
    "CDEFGHJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "E"},
    "CDEFGHKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEFGIJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "CDEFGIJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "CDEFGIKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEFGJKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEFHIJK": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "CDEFHIJL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "CDEFHIKL": {"3-CEFHI": "C", "3-EFGIJ": "E", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEFHJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEFIJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "E", "3-ABCDF": "D", "3-AEHIJ": "I", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "I", "3-EHIJK": "K"},
    "CDEGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "I"},
    "CDEGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDEHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDFGHIJK": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "CDFGHIJL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "CDFGHIKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDFGHJKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDFGIJKL": {"3-CEFHI": "C", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDFHIJKL": {"3-CEFHI": "C", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CDGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "D", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CEFGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "CEFGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "CEFGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CEFGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CEFGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CEFHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CEGHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "CFGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "C", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "DEFGHIJK": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "I", "3-EHIJK": "K"},
    "DEFGHIJL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "I"},
    "DEFGHIKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "DEFGHJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "J", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "DEFGIJKL": {"3-CEFHI": "E", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "DEFHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "DEGHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
    "DFGHIJKL": {"3-CEFHI": "H", "3-EFGIJ": "G", "3-BEFIJ": "I", "3-ABCDF": "D", "3-AEHIJ": "J", "3-CDFGH": "F", "3-DEIJL": "L", "3-EHIJK": "K"},
    "EFGHIJKL": {"3-CEFHI": "E", "3-EFGIJ": "J", "3-BEFIJ": "I", "3-ABCDF": "F", "3-AEHIJ": "H", "3-CDFGH": "G", "3-DEIJL": "L", "3-EHIJK": "K"},
}
