graph TD;
    subgraph django.contrib.admin
        LogEntry
    end

    subgraph django.contrib.auth
        AbstractUser
        Permission
        Group
        User
    end

    subgraph django.contrib.contenttypes
        ContentType
    end

    subgraph django.contrib.sessions
        AbstractBaseSession
        Session
    end

    subgraph bets
        Pais
        Escenario
        Usuario
        Sala
        UsuarioSala
        Deporte
        Competencia
        Equipo
        Deportista
        Partidos
        PartidoFutbol
        PartidoTenis
        PartidoBaloncesto
        CarreraF1
        ApuestaFutbol
        ApuestaTenis
        ApuestaBaloncesto
        ApuestaF1
        Ranking
        MensajeChat
    end

    subgraph rest_framework.authtoken
        Token
        TokenProxy
    end

    LogEntry -->|user| User;
    LogEntry -->|content_type| ContentType;
    AbstractUser --> AbstractBaseUser;
    AbstractUser --> PermissionsMixin;
    Permission -->|content_type| ContentType;
    Group -->|permissions| Permission;
    User -->|groups| Group;
    User -->|user_permissions| Permission;
    User --> AbstractUser;
    Session --> AbstractBaseSession;
    Escenario -->|id_pais| Pais;
    Usuario -->|user| User;
    Sala -->|id_usuario| Usuario;
    UsuarioSala -->|id_usuario| Usuario;
    UsuarioSala -->|id_sala| Sala;
    Competencia -->|id_pais| Pais;
    Competencia -->|id_deporte| Deporte;
    Equipo -->|id_pais| Pais;
    Equipo -->|id_deporte| Deporte;
    Deportista -->|id_pais| Pais;
    Deportista -->|id_equipo| Equipo;
    Deportista -->|id_deporte| Deporte;
    Partidos -->|equipo_local| Equipo;
    Partidos -->|equipo_visitante| Equipo;
    Partidos -->|deportista_local| Deportista;
    Partidos -->|deportista_visitante| Deportista;
    Partidos -->|id_competencia| Competencia;
    Partidos -->|id_escenario| Escenario;
    PartidoFutbol -->|id_partido| Partidos;
    PartidoTenis -->|id_partido| Partidos;
    PartidoBaloncesto -->|id_partido| Partidos;
    CarreraF1 -->|id_escenario| Escenario;
    CarreraF1 -->|id_competencia| Competencia;
    CarreraF1 -->|id_equipo_competencia| Equipo;
    CarreraF1 -->|id_deportista_competencia| Deportista;
    CarreraF1 -->|id_pais_competencia| Pais;
    CarreraF1 -->|id_deportista| Deportista;
    ApuestaFutbol -->|id_usuario| Usuario;
    ApuestaFutbol -->|id_partido| Partidos;
    ApuestaFutbol -->|id_sala| Sala;
    ApuestaTenis -->|id_usuario| Usuario;
    ApuestaTenis -->|id_partido| Partidos;
    ApuestaTenis -->|id_sala| Sala;
    ApuestaBaloncesto -->|id_usuario| Usuario;
    ApuestaBaloncesto -->|id_partido| Partidos;
    ApuestaBaloncesto -->|id_sala| Sala;
    ApuestaF1 -->|id_usuario| Usuario;
    ApuestaF1 -->|id_carrera| CarreraF1;
    ApuestaF1 -->|id_sala| Sala;
    ApuestaF1 -->|prediccion_piloto_1| Deportista;
    ApuestaF1 -->|prediccion_piloto_2| Deportista;
    ApuestaF1 -->|prediccion_piloto_3| Deportista;
    ApuestaF1 -->|prediccion_piloto_4| Deportista;
    ApuestaF1 -->|prediccion_piloto_5| Deportista;
    ApuestaF1 -->|prediccion_piloto_6| Deportista;
    ApuestaF1 -->|prediccion_piloto_7| Deportista;
    ApuestaF1 -->|prediccion_piloto_8| Deportista;
    ApuestaF1 -->|prediccion_piloto_9| Deportista;
    ApuestaF1 -->|prediccion_piloto_10| Deportista;
    ApuestaF1 -->|prediccion_vuelta_rapida| Deportista;
    Ranking -->|id_usuario| Usuario;
    Ranking -->|id_sala| Sala;
    MensajeChat -->|id_sala| Sala;
    MensajeChat -->|id_usuario| Usuario;
    Token -->|user| User;
    TokenProxy --> Token;
