# Generated by Django 5.1.7 on 2025-04-15 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deporte",
            fields=[
                ("id_deporte", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "deportes",
            },
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id_pais", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("continente", models.CharField(max_length=50)),
                ("bandera", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name_plural": "Paises",
                "db_table": "pais",
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                ("id_competencia", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("temporada", models.CharField(blank=True, max_length=10, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id_deporte",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_deporte",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.deporte",
                    ),
                ),
                (
                    "id_pais",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_pais",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.pais",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Competencias",
                "db_table": "competencias",
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                ("id_equipo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id_deporte",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_deporte",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.deporte",
                    ),
                ),
                (
                    "id_pais",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_pais",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.pais",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Equipos",
                "db_table": "equipos",
            },
        ),
        migrations.CreateModel(
            name="Deportista",
            fields=[
                ("id_deportista", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("foto", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "id_deporte",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_deporte",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.deporte",
                    ),
                ),
                (
                    "id_equipo",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_equipo",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.equipo",
                    ),
                ),
                (
                    "id_pais",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_pais",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.pais",
                    ),
                ),
            ],
            options={
                "db_table": "deportista",
            },
        ),
        migrations.CreateModel(
            name="Escenario",
            fields=[
                ("id_escenario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("capacidad", models.IntegerField(blank=True, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "id_pais",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_pais",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.pais",
                    ),
                ),
            ],
            options={
                "db_table": "escenario",
            },
        ),
        migrations.CreateModel(
            name="CarreraF1",
            fields=[
                ("id_carrera_f1", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_carrera", models.DateTimeField(blank=True, null=True)),
                ("vueltas", models.IntegerField(default=0)),
                ("posicion_1", models.IntegerField(default=0)),
                ("posicion_2", models.IntegerField(default=0)),
                ("posicion_3", models.IntegerField(default=0)),
                ("posicion_4", models.IntegerField(default=0)),
                ("posicion_5", models.IntegerField(default=0)),
                ("posicion_6", models.IntegerField(default=0)),
                ("posicion_7", models.IntegerField(default=0)),
                ("posicion_8", models.IntegerField(default=0)),
                ("posicion_9", models.IntegerField(default=0)),
                ("posicion_10", models.IntegerField(default=0)),
                ("vuelta_rapida", models.IntegerField(default=0)),
                (
                    "id_competencia",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_competencia",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.competencia",
                    ),
                ),
                (
                    "id_deportista",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_deportista",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carreras",
                        to="bets.deportista",
                    ),
                ),
                (
                    "id_deportista_competencia",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_deportista_competencia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competencias_deportista",
                        to="bets.deportista",
                    ),
                ),
                (
                    "id_equipo_competencia",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_equipo_competencia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carreras_equipo",
                        to="bets.equipo",
                    ),
                ),
                (
                    "id_escenario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_escenario",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.escenario",
                    ),
                ),
                (
                    "id_pais_competencia",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_pais_competencia",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carreras_pais",
                        to="bets.pais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrera de F1",
                "verbose_name_plural": "Carreras de F1",
                "db_table": "carreras_f1",
            },
        ),
        migrations.CreateModel(
            name="Partidos",
            fields=[
                ("id_partidos", models.AutoField(primary_key=True, serialize=False)),
                ("resultado_local", models.IntegerField(default=0)),
                ("resultado_visitante", models.IntegerField(default=0)),
                ("fecha_partido", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en curso", "En Curso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="programado",
                        max_length=10,
                    ),
                ),
                (
                    "deportista_local",
                    models.ForeignKey(
                        blank=True,
                        db_column="deportista_local",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_local",
                        to="bets.deportista",
                    ),
                ),
                (
                    "deportista_visitante",
                    models.ForeignKey(
                        blank=True,
                        db_column="deportista_visitante",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_visitante",
                        to="bets.deportista",
                    ),
                ),
                (
                    "equipo_local",
                    models.ForeignKey(
                        db_column="equipo_local",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_local",
                        to="bets.equipo",
                    ),
                ),
                (
                    "equipo_visitante",
                    models.ForeignKey(
                        db_column="equipo_visitante",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_visitante",
                        to="bets.equipo",
                    ),
                ),
                (
                    "id_competencia",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_competencia",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.competencia",
                    ),
                ),
                (
                    "id_escenario",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_escenario",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.escenario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Partidos",
                "db_table": "partidos",
            },
        ),
        migrations.CreateModel(
            name="PartidoFutbol",
            fields=[
                (
                    "id_partido_futbol",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("goles_local", models.IntegerField(default=0)),
                ("goles_visitante", models.IntegerField(default=0)),
                ("tarjeta_amarilla_local", models.IntegerField(default=0)),
                ("tarjeta_amarilla_visitante", models.IntegerField(default=0)),
                ("tarjeta_roja_local", models.IntegerField(default=0)),
                ("tarjeta_roja_visitante", models.IntegerField(default=0)),
                ("goles_local_1", models.IntegerField(default=0)),
                ("goles_visitante_1", models.IntegerField(default=0)),
                ("goles_local_2", models.IntegerField(default=0)),
                ("goles_visitante_2", models.IntegerField(default=0)),
                ("penales_local", models.IntegerField(default=0)),
                ("penales_visitante", models.IntegerField(default=0)),
                ("tiros_esquina_local", models.IntegerField(default=0)),
                ("tiros_esquina_visitante", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.OneToOneField(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido de Fútbol",
                "verbose_name_plural": "Partidos de Fútbol",
                "db_table": "partidos_futbol",
            },
        ),
        migrations.CreateModel(
            name="PartidoBaloncesto",
            fields=[
                (
                    "id_partido_baloncesto",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("puntos_local", models.IntegerField(default=0)),
                ("puntos_visitante", models.IntegerField(default=0)),
                ("resultado_local_1", models.IntegerField(default=0)),
                ("resultado_visitante_1", models.IntegerField(default=0)),
                ("resultado_local_2", models.IntegerField(default=0)),
                ("resultado_visitante_2", models.IntegerField(default=0)),
                ("resultado_local_3", models.IntegerField(default=0)),
                ("resultado_visitante_3", models.IntegerField(default=0)),
                ("resultado_local_4", models.IntegerField(default=0)),
                ("resultado_visitante_4", models.IntegerField(default=0)),
                ("rebotes_local", models.IntegerField(default=0)),
                ("rebotes_visitante", models.IntegerField(default=0)),
                ("asistencias_local", models.IntegerField(default=0)),
                ("asistencias_visitante", models.IntegerField(default=0)),
                ("robos_local", models.IntegerField(default=0)),
                ("robos_visitante", models.IntegerField(default=0)),
                ("tapones_local", models.IntegerField(default=0)),
                ("tapones_visitante", models.IntegerField(default=0)),
                ("tiros_libres_local", models.IntegerField(default=0)),
                ("tiros_libres_visitante", models.IntegerField(default=0)),
                ("tiros_3_local", models.IntegerField(default=0)),
                ("tiros_3_visitante", models.IntegerField(default=0)),
                ("faltas_local", models.IntegerField(default=0)),
                ("faltas_visitante", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.OneToOneField(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido de Baloncesto",
                "verbose_name_plural": "Partidos de Baloncesto",
                "db_table": "partidos_baloncesto",
            },
        ),
        migrations.CreateModel(
            name="PartidoTenis",
            fields=[
                (
                    "id_partido_tenis",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("sets_totales", models.IntegerField(default=0)),
                ("games_totales", models.IntegerField(default=0)),
                ("marcador_local_1", models.IntegerField(default=0)),
                ("marcador_visitante_1", models.IntegerField(default=0)),
                ("marcador_local_2", models.IntegerField(default=0)),
                ("marcador_visitante_2", models.IntegerField(default=0)),
                ("marcador_local_3", models.IntegerField(default=0)),
                ("marcador_visitante_3", models.IntegerField(default=0)),
                ("marcador_local_4", models.IntegerField(default=0)),
                ("marcador_visitante_4", models.IntegerField(default=0)),
                ("marcador_local_5", models.IntegerField(default=0)),
                ("marcador_visitante_5", models.IntegerField(default=0)),
                ("aces_local", models.IntegerField(default=0)),
                ("aces_visitante", models.IntegerField(default=0)),
                ("dobles_faltas_local", models.IntegerField(default=0)),
                ("dobles_faltas_visitante", models.IntegerField(default=0)),
                ("max_sets", models.IntegerField(default=0)),
                ("tiebreak_1", models.IntegerField(default=0)),
                ("tiebreak_2", models.IntegerField(default=0)),
                ("tiebreak_3", models.IntegerField(default=0)),
                ("tiebreak_4", models.IntegerField(default=0)),
                ("tiebreak_5", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.OneToOneField(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido de Tenis",
                "verbose_name_plural": "Partidos de Tenis",
                "db_table": "partidos_tenis",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=100, unique=True)),
                ("contrasena", models.CharField(max_length=255)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("puntos_totales", models.IntegerField(default=0)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("apellido", models.CharField(blank=True, max_length=100, null=True)),
                ("celular", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "foto_perfil",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                ("id_sala", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "codigo_sala",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "sala",
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                ("id_ranking", models.AutoField(primary_key=True, serialize=False)),
                ("puntos", models.IntegerField(default=0)),
                ("posicion", models.IntegerField(blank=True, null=True)),
                ("periodo", models.DateField(auto_now_add=True)),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "ranking",
            },
        ),
        migrations.CreateModel(
            name="MensajeChat",
            fields=[
                ("id_mensaje", models.AutoField(primary_key=True, serialize=False)),
                ("contenido", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("eliminado", "Eliminado"),
                            ("reportado", "Reportado"),
                        ],
                        default="activo",
                        max_length=10,
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "db_table": "mensajes_chat",
            },
        ),
        migrations.CreateModel(
            name="ApuestaTenis",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("prediccion_local", models.IntegerField()),
                ("prediccion_visitante", models.IntegerField()),
                ("marcador_local_1", models.IntegerField(default=0)),
                ("marcador_visitante_1", models.IntegerField(default=0)),
                ("marcador_local_2", models.IntegerField(default=0)),
                ("marcador_visitante_2", models.IntegerField(default=0)),
                ("marcador_local_3", models.IntegerField(default=0)),
                ("marcador_visitante_3", models.IntegerField(default=0)),
                ("marcador_local_4", models.IntegerField(default=0)),
                ("marcador_visitante_4", models.IntegerField(default=0)),
                ("marcador_local_5", models.IntegerField(default=0)),
                ("marcador_visitante_5", models.IntegerField(default=0)),
                ("games_totales", models.IntegerField(default=0)),
                ("sets_totales", models.IntegerField(default=0)),
                ("aces_local", models.IntegerField(default=0)),
                ("aces_visitante", models.IntegerField(default=0)),
                ("dobles_faltas_local", models.IntegerField(default=0)),
                ("dobles_faltas_visitante", models.IntegerField(default=0)),
                ("tiebreak_1", models.IntegerField(default=0)),
                ("tiebreak_2", models.IntegerField(default=0)),
                ("tiebreak_3", models.IntegerField(default=0)),
                ("tiebreak_4", models.IntegerField(default=0)),
                ("tiebreak_5", models.IntegerField(default=0)),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.ForeignKey(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidos",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ApuestasTenis",
                "db_table": "apuestasTenis",
            },
        ),
        migrations.CreateModel(
            name="ApuestaFutbol",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("prediccion_local", models.IntegerField()),
                ("prediccion_visitante", models.IntegerField()),
                ("resultado_local_1", models.IntegerField(default=0)),
                ("resultado_visitante_1", models.IntegerField(default=0)),
                ("resultado_local_2", models.IntegerField(default=0)),
                ("resultado_visitante_2", models.IntegerField(default=0)),
                ("tarjeta_amarilla_local", models.IntegerField(default=0)),
                ("tarjeta_amarilla_visitante", models.IntegerField(default=0)),
                ("tarjeta_roja_local", models.IntegerField(default=0)),
                ("tarjeta_roja_visitante", models.IntegerField(default=0)),
                ("tiros_esquina_local", models.IntegerField(default=0)),
                ("tiros_esquina_visitante", models.IntegerField(default=0)),
                ("penales_local", models.IntegerField(default=0)),
                ("penales_visitante", models.IntegerField(default=0)),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.ForeignKey(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidos",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ApuestasFutbol",
                "db_table": "apuestasFutbol",
            },
        ),
        migrations.CreateModel(
            name="ApuestaF1",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                (
                    "id_carrera",
                    models.ForeignKey(
                        db_column="id_carrera",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.carreraf1",
                    ),
                ),
                (
                    "prediccion_piloto_1",
                    models.ForeignKey(
                        db_column="prediccion_piloto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_10",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_10",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_10",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_2",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_2",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_2",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_3",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_3",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_3",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_4",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_4",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_4",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_5",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_5",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_5",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_6",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_6",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_6",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_7",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_7",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_7",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_8",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_8",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_8",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_piloto_9",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_piloto_9",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_9",
                        to="bets.deportista",
                    ),
                ),
                (
                    "prediccion_vuelta_rapida",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediccion_vuelta_rapida",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_vuelta_rapida",
                        to="bets.deportista",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ApuestasF1",
                "db_table": "apuestasF1",
            },
        ),
        migrations.CreateModel(
            name="ApuestaBaloncesto",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("prediccion_local", models.IntegerField()),
                ("prediccion_visitante", models.IntegerField()),
                ("resultado_local_1", models.IntegerField(default=0)),
                ("resultado_visitante_1", models.IntegerField(default=0)),
                ("resultado_local_2", models.IntegerField(default=0)),
                ("resultado_visitante_2", models.IntegerField(default=0)),
                ("resultado_local_3", models.IntegerField(default=0)),
                ("resultado_visitante_3", models.IntegerField(default=0)),
                ("resultado_local_4", models.IntegerField(default=0)),
                ("resultado_visitante_4", models.IntegerField(default=0)),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.ForeignKey(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidos",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ApuestasBaloncesto",
                "db_table": "apuestasBaloncesto",
            },
        ),
        migrations.CreateModel(
            name="UsuarioSala",
            fields=[
                (
                    "id_usuario_sala",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("rol", models.CharField(default="participante", max_length=50)),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "usuario_sala",
            },
        ),
        migrations.AddIndex(
            model_name="partidos",
            index=models.Index(fields=["estado"], name="partidos_estado_3c646e_idx"),
        ),
        migrations.AddIndex(
            model_name="partidos",
            index=models.Index(
                fields=["fecha_partido"], name="partidos_fecha_p_e04d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partidos",
            index=models.Index(
                fields=["id_competencia"], name="partidos_id_comp_597cbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(
                fields=["id_usuario"], name="ranking_id_usua_355243_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(fields=["id_sala"], name="ranking_id_sala_89f64f_idx"),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(fields=["periodo"], name="ranking_periodo_9ad124_idx"),
        ),
        migrations.AddIndex(
            model_name="mensajechat",
            index=models.Index(
                fields=["id_sala"], name="mensajes_ch_id_sala_ba9775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajechat",
            index=models.Index(
                fields=["id_usuario"], name="mensajes_ch_id_usua_736761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajechat",
            index=models.Index(
                fields=["fecha_envio"], name="mensajes_ch_fecha_e_696c78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestatenis",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestasTen_id_usua_363ad3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestatenis",
            index=models.Index(
                fields=["id_partido"], name="apuestasTen_id_part_615803_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestatenis",
            index=models.Index(fields=["estado"], name="apuestasTen_estado_997fdf_idx"),
        ),
        migrations.AddIndex(
            model_name="apuestafutbol",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestasFut_id_usua_652941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestafutbol",
            index=models.Index(
                fields=["id_partido"], name="apuestasFut_id_part_f1ad63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestafutbol",
            index=models.Index(fields=["estado"], name="apuestasFut_estado_dce56d_idx"),
        ),
        migrations.AddIndex(
            model_name="apuestaf1",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestasF1_id_usua_e5a9af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestaf1",
            index=models.Index(
                fields=["id_carrera"], name="apuestasF1_id_carr_7e5202_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestaf1",
            index=models.Index(fields=["estado"], name="apuestasF1_estado_fde614_idx"),
        ),
        migrations.AddIndex(
            model_name="apuestabaloncesto",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestasBal_id_usua_815c72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestabaloncesto",
            index=models.Index(
                fields=["id_partido"], name="apuestasBal_id_part_4d20b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestabaloncesto",
            index=models.Index(fields=["estado"], name="apuestasBal_estado_2d6c1b_idx"),
        ),
        migrations.AddIndex(
            model_name="usuariosala",
            index=models.Index(
                fields=["id_usuario"], name="usuario_sal_id_usua_b1c217_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuariosala",
            index=models.Index(
                fields=["id_sala"], name="usuario_sal_id_sala_1a47a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usuariosala",
            unique_together={("id_usuario", "id_sala")},
        ),
    ]
