# Generated by Django 5.1.7 on 2025-04-16 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiEquipo",
            fields=[
                ("id_equipo", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "nombre_corto",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("logo_url", models.CharField(blank=True, max_length=255, null=True)),
                ("api_id", models.IntegerField(blank=True, null=True)),
                ("fundado", models.IntegerField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "API Equipos",
                "db_table": "api_equipos",
            },
        ),
        migrations.CreateModel(
            name="ApiPais",
            fields=[
                ("id_pais", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "bandera_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("api_id", models.IntegerField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "API Paises",
                "db_table": "api_paises",
            },
        ),
        migrations.CreateModel(
            name="Deporte",
            fields=[
                ("id_deporte", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("api_sport_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "deportes",
            },
        ),
        migrations.CreateModel(
            name="ApiLiga",
            fields=[
                ("id_liga", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "temporada_actual",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("logo_url", models.CharField(blank=True, max_length=255, null=True)),
                ("api_id", models.IntegerField(blank=True, null=True)),
                ("tiene_eventos", models.BooleanField(default=False)),
                ("tiene_alineaciones", models.BooleanField(default=False)),
                ("tiene_estadisticas", models.BooleanField(default=False)),
                ("tiene_clasificacion", models.BooleanField(default=False)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_pais",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apipais",
                    ),
                ),
                (
                    "id_deporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.deporte",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "API Ligas",
                "db_table": "api_ligas",
            },
        ),
        migrations.CreateModel(
            name="ApiJugador",
            fields=[
                ("id_jugador", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("api_id", models.IntegerField(blank=True, null=True)),
                ("foto_url", models.CharField(blank=True, max_length=255, null=True)),
                ("posicion", models.CharField(blank=True, max_length=50, null=True)),
                ("numero", models.IntegerField(blank=True, null=True)),
                ("edad", models.IntegerField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apiequipo",
                    ),
                ),
                (
                    "id_pais",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apipais",
                    ),
                ),
                (
                    "id_deporte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.deporte",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "API Jugadores",
                "db_table": "api_jugadores",
            },
        ),
        migrations.AddField(
            model_name="apiequipo",
            name="id_pais",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bets.apipais",
            ),
        ),
        migrations.CreateModel(
            name="ApiSyncLog",
            fields=[
                ("id_sync", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_sincronizacion", models.CharField(max_length=50)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("estado", models.CharField(max_length=20)),
                ("detalles", models.TextField(blank=True, null=True)),
                ("registros_procesados", models.IntegerField(default=0)),
                ("id_liga", models.IntegerField(blank=True, null=True)),
                ("temporada", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "verbose_name": "API Sync Log",
                "verbose_name_plural": "API Sync Logs",
                "db_table": "api_sync_log",
                "indexes": [
                    models.Index(
                        fields=["tipo_sincronizacion"],
                        name="api_sync_lo_tipo_si_e383cf_idx",
                    ),
                    models.Index(
                        fields=["fecha_inicio"], name="api_sync_lo_fecha_i_fcc434_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="api_sync_lo_estado_8cf15b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ApiVenue",
            fields=[
                ("id_venue", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("capacidad", models.IntegerField(blank=True, null=True)),
                ("superficie", models.CharField(blank=True, max_length=50, null=True)),
                ("api_id", models.IntegerField(blank=True, null=True)),
                ("imagen_url", models.CharField(blank=True, max_length=255, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_pais",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apipais",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "API Venues",
                "db_table": "api_venues",
            },
        ),
        migrations.CreateModel(
            name="ApiPartido",
            fields=[
                ("id_partido", models.AutoField(primary_key=True, serialize=False)),
                ("api_fixture_id", models.IntegerField(unique=True)),
                ("temporada", models.CharField(max_length=10)),
                ("fecha", models.DateTimeField()),
                ("ronda", models.CharField(blank=True, max_length=50, null=True)),
                ("goles_local", models.IntegerField(blank=True, null=True)),
                ("goles_visitante", models.IntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en curso", "En Curso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                            ("pospuesto", "Pospuesto"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="programado",
                        max_length=20,
                    ),
                ),
                (
                    "tiempo_partido",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("eventos_cargados", models.BooleanField(default=False)),
                ("alineaciones_cargadas", models.BooleanField(default=False)),
                ("estadisticas_cargadas", models.BooleanField(default=False)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "equipo_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_local",
                        to="bets.apiequipo",
                    ),
                ),
                (
                    "equipo_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_visitante",
                        to="bets.apiequipo",
                    ),
                ),
                (
                    "id_liga",
                    models.ForeignKey(
                        db_column="id_liga",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.apiliga",
                    ),
                ),
                (
                    "id_venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apivenue",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "API Partidos",
                "db_table": "api_partidos",
            },
        ),
        migrations.CreateModel(
            name="CarreraF1",
            fields=[
                ("id_carrera_f1", models.AutoField(primary_key=True, serialize=False)),
                (
                    "api_fixture_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("temporada", models.CharField(blank=True, max_length=10, null=True)),
                ("nombre_gp", models.CharField(max_length=100)),
                ("fecha", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en curso", "En Curso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                            ("pospuesto", "Pospuesto"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="programado",
                        max_length=20,
                    ),
                ),
                ("resultados", models.JSONField(blank=True, null=True)),
                ("pilotos_puntos", models.JSONField(blank=True, null=True)),
                ("vuelta_rapida", models.IntegerField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_liga",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_liga",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.apiliga",
                    ),
                ),
                (
                    "id_venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apivenue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrera de F1",
                "verbose_name_plural": "Carreras de F1",
                "db_table": "carreras_f1",
            },
        ),
        migrations.AddField(
            model_name="apiequipo",
            name="id_deporte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bets.deporte",
            ),
        ),
        migrations.CreateModel(
            name="PartidoBaloncesto",
            fields=[
                (
                    "id_partido_baloncesto",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "api_fixture_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("temporada", models.CharField(blank=True, max_length=10, null=True)),
                ("puntos_local", models.IntegerField(blank=True, null=True)),
                ("puntos_visitante", models.IntegerField(blank=True, null=True)),
                ("q1_local", models.IntegerField(blank=True, null=True)),
                ("q1_visitante", models.IntegerField(blank=True, null=True)),
                ("q2_local", models.IntegerField(blank=True, null=True)),
                ("q2_visitante", models.IntegerField(blank=True, null=True)),
                ("q3_local", models.IntegerField(blank=True, null=True)),
                ("q3_visitante", models.IntegerField(blank=True, null=True)),
                ("q4_local", models.IntegerField(blank=True, null=True)),
                ("q4_visitante", models.IntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en curso", "En Curso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                            ("pospuesto", "Pospuesto"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="programado",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("estadisticas", models.JSONField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "equipo_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_baloncesto_local",
                        to="bets.apiequipo",
                    ),
                ),
                (
                    "equipo_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_baloncesto_visitante",
                        to="bets.apiequipo",
                    ),
                ),
                (
                    "id_liga",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_liga",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.apiliga",
                    ),
                ),
                (
                    "id_venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apivenue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido de Baloncesto",
                "verbose_name_plural": "Partidos de Baloncesto",
                "db_table": "partidos_baloncesto",
            },
        ),
        migrations.CreateModel(
            name="PartidoTenis",
            fields=[
                (
                    "id_partido_tenis",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "api_fixture_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("temporada", models.CharField(blank=True, max_length=10, null=True)),
                ("sets_local", models.IntegerField(default=0)),
                ("sets_visitante", models.IntegerField(default=0)),
                ("set1_local", models.IntegerField(blank=True, null=True)),
                ("set1_visitante", models.IntegerField(blank=True, null=True)),
                ("set2_local", models.IntegerField(blank=True, null=True)),
                ("set2_visitante", models.IntegerField(blank=True, null=True)),
                ("set3_local", models.IntegerField(blank=True, null=True)),
                ("set3_visitante", models.IntegerField(blank=True, null=True)),
                ("set4_local", models.IntegerField(blank=True, null=True)),
                ("set4_visitante", models.IntegerField(blank=True, null=True)),
                ("set5_local", models.IntegerField(blank=True, null=True)),
                ("set5_visitante", models.IntegerField(blank=True, null=True)),
                ("aces_local", models.IntegerField(blank=True, null=True)),
                ("aces_visitante", models.IntegerField(blank=True, null=True)),
                ("dobles_faltas_local", models.IntegerField(blank=True, null=True)),
                ("dobles_faltas_visitante", models.IntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en curso", "En Curso"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                            ("pospuesto", "Pospuesto"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="programado",
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_liga",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_liga",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.apiliga",
                    ),
                ),
                (
                    "id_venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bets.apivenue",
                    ),
                ),
                (
                    "jugador_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_tenis_local",
                        to="bets.apijugador",
                    ),
                ),
                (
                    "jugador_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_tenis_visitante",
                        to="bets.apijugador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido de Tenis",
                "verbose_name_plural": "Partidos de Tenis",
                "db_table": "partidos_tenis",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=100, unique=True)),
                ("contrasena", models.CharField(max_length=255)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("puntos_totales", models.IntegerField(default=0)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("apellido", models.CharField(blank=True, max_length=100, null=True)),
                ("celular", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "foto_perfil",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                ("id_sala", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "codigo_sala",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "sala",
            },
        ),
        migrations.CreateModel(
            name="Ranking",
            fields=[
                ("id_ranking", models.AutoField(primary_key=True, serialize=False)),
                ("puntos", models.IntegerField(default=0)),
                ("posicion", models.IntegerField(blank=True, null=True)),
                ("periodo", models.DateField()),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "ranking",
            },
        ),
        migrations.CreateModel(
            name="MensajeChat",
            fields=[
                ("id_mensaje", models.AutoField(primary_key=True, serialize=False)),
                ("contenido", models.TextField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("eliminado", "Eliminado"),
                            ("reportado", "Reportado"),
                        ],
                        default="activo",
                        max_length=10,
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Chat",
                "verbose_name_plural": "Mensajes de Chat",
                "db_table": "mensajes_chat",
            },
        ),
        migrations.CreateModel(
            name="ApuestaTenis",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("prediccion_sets_local", models.IntegerField()),
                ("prediccion_sets_visitante", models.IntegerField()),
                ("prediccion_set1_local", models.IntegerField(blank=True, null=True)),
                (
                    "prediccion_set1_visitante",
                    models.IntegerField(blank=True, null=True),
                ),
                ("prediccion_set2_local", models.IntegerField(blank=True, null=True)),
                (
                    "prediccion_set2_visitante",
                    models.IntegerField(blank=True, null=True),
                ),
                ("prediccion_set3_local", models.IntegerField(blank=True, null=True)),
                (
                    "prediccion_set3_visitante",
                    models.IntegerField(blank=True, null=True),
                ),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.ForeignKey(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidotenis",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Apuestas Tenis",
                "db_table": "apuestas_tenis",
            },
        ),
        migrations.CreateModel(
            name="ApuestaFutbol",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("prediccion_local", models.IntegerField()),
                ("prediccion_visitante", models.IntegerField()),
                ("primer_tiempo_local", models.IntegerField(blank=True, null=True)),
                ("primer_tiempo_visitante", models.IntegerField(blank=True, null=True)),
                ("segundo_tiempo_local", models.IntegerField(blank=True, null=True)),
                (
                    "segundo_tiempo_visitante",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "tarjetas_amarillas_total",
                    models.IntegerField(blank=True, null=True),
                ),
                ("tarjetas_rojas_total", models.IntegerField(blank=True, null=True)),
                ("corners_total", models.IntegerField(blank=True, null=True)),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                ("reglas_puntuacion", models.JSONField(blank=True, null=True)),
                (
                    "id_partido",
                    models.ForeignKey(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.apipartido",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Apuestas Fútbol",
                "db_table": "apuestas_futbol",
            },
        ),
        migrations.CreateModel(
            name="ApuestaF1",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("predicciones_adicionales", models.JSONField(blank=True, null=True)),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                (
                    "prediccion_p1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_p1",
                        to="bets.apijugador",
                    ),
                ),
                (
                    "prediccion_p2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_p2",
                        to="bets.apijugador",
                    ),
                ),
                (
                    "prediccion_p3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_p3",
                        to="bets.apijugador",
                    ),
                ),
                (
                    "prediccion_vuelta_rapida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuestas_f1_vuelta_rapida",
                        to="bets.apijugador",
                    ),
                ),
                (
                    "id_carrera",
                    models.ForeignKey(
                        db_column="id_carrera",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.carreraf1",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Apuestas F1",
                "db_table": "apuestas_f1",
            },
        ),
        migrations.CreateModel(
            name="ApuestaBaloncesto",
            fields=[
                ("id_apuesta", models.AutoField(primary_key=True, serialize=False)),
                ("prediccion_local", models.IntegerField()),
                ("prediccion_visitante", models.IntegerField()),
                ("prediccion_q1_local", models.IntegerField(blank=True, null=True)),
                ("prediccion_q1_visitante", models.IntegerField(blank=True, null=True)),
                ("prediccion_q2_local", models.IntegerField(blank=True, null=True)),
                ("prediccion_q2_visitante", models.IntegerField(blank=True, null=True)),
                ("fecha_apuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ganada", "Ganada"),
                            ("perdida", "Perdida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("puntos_ganados", models.IntegerField(default=0)),
                (
                    "id_partido",
                    models.ForeignKey(
                        db_column="id_partido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.partidobaloncesto",
                    ),
                ),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Apuestas Baloncesto",
                "db_table": "apuestas_baloncesto",
            },
        ),
        migrations.CreateModel(
            name="UsuarioSala",
            fields=[
                (
                    "id_usuario_sala",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("rol", models.CharField(default="participante", max_length=50)),
                (
                    "id_sala",
                    models.ForeignKey(
                        db_column="id_sala",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.sala",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bets.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "usuario_sala",
            },
        ),
        migrations.CreateModel(
            name="ApiPartidoAlineacion",
            fields=[
                ("id_alineacion", models.AutoField(primary_key=True, serialize=False)),
                ("formacion", models.CharField(blank=True, max_length=20, null=True)),
                ("id_entrenador", models.IntegerField(blank=True, null=True)),
                (
                    "nombre_entrenador",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("titulares", models.JSONField(blank=True, null=True)),
                ("suplentes", models.JSONField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bets.apiequipo"
                    ),
                ),
                (
                    "id_partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alineaciones",
                        to="bets.apipartido",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "API Partido Alineaciones",
                "db_table": "api_partido_alineaciones",
                "unique_together": {("id_partido", "id_equipo")},
            },
        ),
        migrations.CreateModel(
            name="ApiPartidoEstadisticas",
            fields=[
                ("id_estadistica", models.AutoField(primary_key=True, serialize=False)),
                ("posesion", models.FloatField(blank=True, null=True)),
                ("tiros_total", models.IntegerField(blank=True, null=True)),
                ("tiros_a_puerta", models.IntegerField(blank=True, null=True)),
                ("tiros_fuera", models.IntegerField(blank=True, null=True)),
                ("tiros_bloqueados", models.IntegerField(blank=True, null=True)),
                ("corners", models.IntegerField(blank=True, null=True)),
                ("offsides", models.IntegerField(blank=True, null=True)),
                ("faltas", models.IntegerField(blank=True, null=True)),
                ("tarjetas_amarillas", models.IntegerField(blank=True, null=True)),
                ("tarjetas_rojas", models.IntegerField(blank=True, null=True)),
                ("estadisticas_extra", models.JSONField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "id_equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bets.apiequipo"
                    ),
                ),
                (
                    "id_partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estadisticas",
                        to="bets.apipartido",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "API Partido Estadísticas",
                "db_table": "api_partido_estadisticas",
                "unique_together": {("id_partido", "id_equipo")},
            },
        ),
        migrations.CreateModel(
            name="ApiPartidoEvento",
            fields=[
                ("id_evento", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_evento", models.CharField(max_length=50)),
                ("minuto", models.IntegerField()),
                ("detalles", models.JSONField(blank=True, null=True)),
                (
                    "id_equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bets.apiequipo"
                    ),
                ),
                (
                    "id_jugador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="bets.apijugador",
                    ),
                ),
                (
                    "id_jugador_asistencia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asistencias",
                        to="bets.apijugador",
                    ),
                ),
                (
                    "id_partido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="bets.apipartido",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "API Partido Eventos",
                "db_table": "api_partido_eventos",
                "indexes": [
                    models.Index(
                        fields=["id_partido", "tipo_evento"],
                        name="api_partido_id_part_50ad35_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="apipartido",
            index=models.Index(
                fields=["api_fixture_id"], name="api_partido_api_fix_20f1f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apipartido",
            index=models.Index(fields=["fecha"], name="api_partido_fecha_c3020a_idx"),
        ),
        migrations.AddIndex(
            model_name="apipartido",
            index=models.Index(fields=["estado"], name="api_partido_estado_e539bc_idx"),
        ),
        migrations.AddIndex(
            model_name="apipartido",
            index=models.Index(
                fields=["id_liga", "temporada"], name="api_partido_id_liga_0a6c08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(
                fields=["id_usuario"], name="ranking_id_usua_355243_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(fields=["id_sala"], name="ranking_id_sala_89f64f_idx"),
        ),
        migrations.AddIndex(
            model_name="ranking",
            index=models.Index(fields=["periodo"], name="ranking_periodo_9ad124_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ranking",
            unique_together={("id_usuario", "id_sala", "periodo")},
        ),
        migrations.AddIndex(
            model_name="mensajechat",
            index=models.Index(
                fields=["id_sala"], name="mensajes_ch_id_sala_ba9775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajechat",
            index=models.Index(
                fields=["id_usuario"], name="mensajes_ch_id_usua_736761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajechat",
            index=models.Index(
                fields=["fecha_envio"], name="mensajes_ch_fecha_e_696c78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestatenis",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestas_te_id_usua_71e8d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestatenis",
            index=models.Index(
                fields=["id_partido"], name="apuestas_te_id_part_cbfe8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestatenis",
            index=models.Index(fields=["estado"], name="apuestas_te_estado_d370d1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="apuestatenis",
            unique_together={("id_usuario", "id_partido", "id_sala")},
        ),
        migrations.AddIndex(
            model_name="apuestafutbol",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestas_fu_id_usua_59e0ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestafutbol",
            index=models.Index(
                fields=["id_partido"], name="apuestas_fu_id_part_077684_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestafutbol",
            index=models.Index(fields=["estado"], name="apuestas_fu_estado_c186f5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="apuestafutbol",
            unique_together={("id_usuario", "id_partido", "id_sala")},
        ),
        migrations.AddIndex(
            model_name="apuestaf1",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestas_f1_id_usua_a5ea67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestaf1",
            index=models.Index(
                fields=["id_carrera"], name="apuestas_f1_id_carr_fa87ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestaf1",
            index=models.Index(fields=["estado"], name="apuestas_f1_estado_8377bd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="apuestaf1",
            unique_together={("id_usuario", "id_carrera", "id_sala")},
        ),
        migrations.AddIndex(
            model_name="apuestabaloncesto",
            index=models.Index(
                fields=["id_usuario", "id_sala"], name="apuestas_ba_id_usua_7a7096_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestabaloncesto",
            index=models.Index(
                fields=["id_partido"], name="apuestas_ba_id_part_227a02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apuestabaloncesto",
            index=models.Index(fields=["estado"], name="apuestas_ba_estado_e68a29_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="apuestabaloncesto",
            unique_together={("id_usuario", "id_partido", "id_sala")},
        ),
        migrations.AddIndex(
            model_name="usuariosala",
            index=models.Index(
                fields=["id_usuario"], name="usuario_sal_id_usua_b1c217_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usuariosala",
            index=models.Index(
                fields=["id_sala"], name="usuario_sal_id_sala_1a47a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usuariosala",
            unique_together={("id_usuario", "id_sala")},
        ),
    ]
