# Generated by Django 5.2.5 on 2025-08-09 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidos',
            name='id_deporte',
            field=models.ForeignKey(blank=True, db_column='id_deporte', null=True, on_delete=django.db.models.deletion.CASCADE, to='bets.deporte'),
        ),
        migrations.AddIndex(
            model_name='partidos',
            index=models.Index(fields=['id_deporte'], name='partidos_id_depo_710dae_idx'),
        ),
    ]
