# Generated by Django 5.2.5 on 2025-12-18 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_add_tipo_field_to_apiequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaDeporte',
            fields=[
                ('id_sala_deporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('id_deporte', models.ForeignKey(db_column='id_deporte', on_delete=django.db.models.deletion.CASCADE, to='bets.deporte')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='deportes_habilitados', to='bets.sala')),
            ],
            options={
                'verbose_name': 'Deporte de Sala',
                'verbose_name_plural': 'Deportes de Sala',
                'db_table': 'sala_deporte',
                'unique_together': {('id_sala', 'id_deporte')},
            },
        ),
        migrations.CreateModel(
            name='SalaLiga',
            fields=[
                ('id_sala_liga', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('id_liga', models.ForeignKey(db_column='id_liga', on_delete=django.db.models.deletion.CASCADE, to='bets.apiliga')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='ligas_habilitadas', to='bets.sala')),
            ],
            options={
                'verbose_name': 'Liga de Sala',
                'verbose_name_plural': 'Ligas de Sala',
                'db_table': 'sala_liga',
                'indexes': [models.Index(fields=['id_sala'], name='sala_liga_id_sala_968f2b_idx'), models.Index(fields=['id_liga'], name='sala_liga_id_liga_601686_idx')],
                'unique_together': {('id_sala', 'id_liga')},
            },
        ),
        migrations.CreateModel(
            name='SalaPartido',
            fields=[
                ('id_sala_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('agregado_por', models.ForeignKey(db_column='agregado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.usuario')),
                ('id_partido', models.ForeignKey(db_column='id_partido', on_delete=django.db.models.deletion.CASCADE, to='bets.apipartido')),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='partidos_habilitados', to='bets.sala')),
            ],
            options={
                'verbose_name': 'Partido de Sala',
                'verbose_name_plural': 'Partidos de Sala',
                'db_table': 'sala_partido',
                'indexes': [models.Index(fields=['id_sala'], name='sala_partid_id_sala_849c43_idx'), models.Index(fields=['id_partido'], name='sala_partid_id_part_6366fb_idx')],
                'unique_together': {('id_sala', 'id_partido')},
            },
        ),
    ]
