# Generated by Django 5.2.5 on 2025-12-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_usuario_email_verified_emailverificationtoken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='modo_sala',
            field=models.CharField(choices=[('ligas', 'Ligas/Torneos'), ('partidos_individuales', 'Partidos Individuales'), ('mixto', 'Mixto (Ligas + Partidos Individuales)')], default='ligas', max_length=30),
        ),
    ]
