# Generated by Django 5.2.5 on 2025-12-25 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_sala_modo_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaNotificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('nuevo_miembro', 'Nuevo Miembro'), ('nuevo_lider', 'Nuevo Líder'), ('resultado_partido', 'Resultado de Partido'), ('nuevo_partido', 'Nuevo Partido Agregado'), ('nueva_liga', 'Nueva Liga Agregada'), ('custom', 'Notificación Personalizada')], max_length=30)),
                ('mensaje', models.TextField()),
                ('icono', models.CharField(default='🔔', max_length=50)),
                ('color', models.CharField(default='text-blue-500', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_sala', models.ForeignKey(db_column='id_sala', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='bets.sala')),
                ('partido_relacionado', models.ForeignKey(blank=True, db_column='partido_relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.apipartido')),
                ('usuario_relacionado', models.ForeignKey(blank=True, db_column='usuario_relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bets.usuario')),
            ],
            options={
                'verbose_name': 'Notificación de Sala',
                'verbose_name_plural': 'Notificaciones de Sala',
                'db_table': 'sala_notificacion',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['id_sala', '-fecha'], name='sala_notifi_id_sala_83b541_idx'), models.Index(fields=['tipo'], name='sala_notifi_tipo_33f4d9_idx')],
            },
        ),
    ]
