# Generated by Django 5.2.5 on 2026-06-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_usuariosala_ultima_notificacion_vista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salanotificacion',
            name='tipo',
            field=models.CharField(choices=[('nuevo_miembro', 'Nuevo Miembro'), ('nuevo_lider', 'Nuevo Líder'), ('resultado_partido', 'Resultado de Partido'), ('nuevo_partido', 'Nuevo Partido Agregado'), ('nueva_liga', 'Nueva Liga Agregada'), ('recordatorio_partido', 'Recordatorio de Partido'), ('nuevo_mensaje_chat', 'Nuevo Mensaje de Chat'), ('custom', 'Notificación Personalizada')], max_length=30),
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to='bets.usuario')),
            ],
            options={
                'db_table': 'login_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', '-timestamp'], name='login_event_usuario_d59ade_idx')],
            },
        ),
    ]
