# Generated by Django 5.2.5 on 2026-06-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0012_worldcupprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipartido',
            name='is_knockout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apuestafutbol',
            name='ganador_ko',
            field=models.ForeignKey(blank=True, db_column='ganador_ko', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apuestas_ko_ganador', to='bets.apiequipo'),
        ),
        migrations.AddField(
            model_name='apuestafutbol',
            name='tiene_penales',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apuestafutbol',
            name='tiene_tiempo_extra',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
